#include "globals.h"
#include "communications.h"
#include "throttle_control.h"
#include "oscc_can.h"
#include "oscc.h"
#include "can_protocols/throttle_can_protocol.h"
#include "can_protocols/fault_can_protocol.h"
#include "vehicles/kia_soul.h"
